New Updates
mitre/google-chrome-v2r6-stig-baseline pull request #4
Opened 2022-08-03 18:15 UTC by TSterling76

2022-08-03 18:15 UTC, TSterling76 commented
@aaronlippold @camdenmoors

2022-08-11 14:22 UTC, em-c-rod commented
How did you test this on your end? It would be good to add a GitHub workflow to automatically test this profile.

2022-08-11 14:57 UTC, TSterling76 commented
I test  by running Inspec on each file. I'm not sure how to set up a Github workflow here.

2022-08-12 18:26 UTC, HenryXiaoHX requested changes

2022-08-12 18:26 UTC, HenryXiaoHX commented on controls/SV-221580.rb
> +    describe registry_key('HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\') do
The last backslash in the registry_key path, the backslash after Chrome, serves as an escape character and have escaped the single quote after it. Consider removing the backslash or adding an extra backlash to fix the syntax.

2022-08-12 18:26 UTC, HenryXiaoHX commented on controls/SV-221586.rb
> +    its('\"AllowDeletingBrowserHistory\"') { should cmp '\"0\"' }
The combination of backslash followed by double quotes,`\"`, is not necessary. It checks for `\"AllowDeletingBrowserHistory\"` as opposed to `AllowDeletingBrowserHistory` as the property. Similarly, it checks for `\"0\"` as opposed to `0` as the value. Consider removing this combination `\"` to fix the syntax.

2022-08-12 18:26 UTC, HenryXiaoHX commented on controls/SV-221587.rb
> +    it { should have_property '\"PromptForDownloadLocation\"'}
The combination of backslash followed by double quotes,`\"`, is not necessary. It checks for `\"PromptForDownloadLocation\"` as opposed to `PromptForDownloadLocation` as the property. Similarly, it checks for `\"1\"` as opposed to `1` as the value. Consider removing this combination `\"` to fix the syntax.

2022-08-16 16:04 UTC, TSterling76 commented
Are you seeing the changes?

2022-08-16 16:46 UTC, HenryXiaoHX approved these changes

2022-08-16 19:19 UTC, merged